# Generated by Django 4.1.6 on 2023-04-10 12:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cardExpDate", models.DateField()),
                (
                    "zipCode",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(10000),
                            django.core.validators.MaxValueValidator(99999),
                        ]
                    ),
                ),
                ("ammountCharge", models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
