# Generated by Django 4.1.6 on 2023-04-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_remove_bill_ammountcharge"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="total_due",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9999),
        ),
    ]
