# Generated by Django 4.1.6 on 2023-04-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_bill_total_due"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bill",
            name="total_due",
        ),
        migrations.AlterField(
            model_name="bill",
            name="creditCardNumber",
            field=models.IntegerField(),
        ),
    ]
