# Generated by Django 4.1.6 on 2023-04-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="courtReservationForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "courtNumber",
                    models.IntegerField(
                        choices=[
                            (1, "Court 1"),
                            (2, "Court 2"),
                            (3, "Court 3"),
                            (4, "Court 4"),
                            (5, "Court 5"),
                            (6, "Court 6"),
                            (7, "Court 7"),
                            (8, "Court 8"),
                            (9, "Court 9"),
                            (10, "Court 10"),
                            (11, "Court 11"),
                            (12, "Court 12"),
                        ]
                    ),
                ),
                (
                    "courtTime",
                    models.CharField(
                        choices=[
                            ("8:00 - 9:30", "8:00 - 9:30"),
                            ("9:30 - 11:00", "9:30 - 11:00"),
                            ("11:00 - 12:30", "11:00 - 12:30"),
                            ("12:30 - 2:00", "12:30 - 2:00"),
                            ("2:00 - 3:30", "2:00 - 3:30"),
                            ("3:30 - 5:00", "3:30 - 5:00"),
                        ],
                        max_length=20,
                    ),
                ),
                ("guest1EMail", models.EmailField(blank=True, max_length=254)),
                ("guest1FName", models.CharField(blank=True, max_length=100)),
                ("guest1LName", models.CharField(blank=True, max_length=100)),
                ("guest2EMail", models.EmailField(blank=True, max_length=254)),
                ("guest2FName", models.CharField(blank=True, max_length=100)),
                ("guest2LName", models.CharField(blank=True, max_length=100)),
                ("guest3EMail", models.EmailField(blank=True, max_length=254)),
                ("guest3FName", models.CharField(blank=True, max_length=100)),
                ("guest3LName", models.CharField(blank=True, max_length=100)),
                ("guest4EMail", models.EmailField(blank=True, max_length=254)),
                ("guest4FName", models.CharField(blank=True, max_length=100)),
                ("guest4LName", models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
