# Generated by Django 4.1.6 on 2023-03-31 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="courtReservationForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guest1EMail", models.EmailField(max_length=254)),
                ("guest1FName", models.CharField(max_length=100)),
                ("guest1LName", models.CharField(max_length=100)),
                ("guest2EMail", models.EmailField(max_length=254)),
                ("guest2FName", models.CharField(max_length=100)),
                ("guest2LName", models.CharField(max_length=100)),
                ("guest3EMail", models.EmailField(max_length=254)),
                ("guest3FName", models.CharField(max_length=100)),
                ("guest3LName", models.CharField(max_length=100)),
            ],
        ),
    ]
