# Generated by Django 4.1.6 on 2023-04-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courts", "0002_alter_courtreservationform_guest1email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="courtreservationform",
            name="courtNumber",
            field=models.IntegerField(
                choices=[(1, "Court 1"), (2, "Court 2")], default=0
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="courtreservationform",
            name="courtTime",
            field=models.CharField(
                choices=[
                    ("8:00 - 9:30", "8:00 - 9:30"),
                    ("9:30 - 11:00", "9:30 - 11:00"),
                    ("11:00 - 12:30", "11:00-12:30"),
                    ("12:30 - 2:00", "12:30 - 2:00"),
                    ("2:00-3:30", "2:00-3:30"),
                    ("3:30 - 5:00", "3:30 - 5:00"),
                ],
                default=0,
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
