# Generated by Django 4.1.6 on 2023-04-19 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courts", "0003_courtreservationform_courtdate"),
    ]

    operations = [
        migrations.DeleteModel(
            name="dayMenu",
        ),
    ]
