# Generated by Django 4.1.6 on 2023-04-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courts", "0003_courtreservationform_courtnumber_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="courtreservationform",
            name="guest4EMail",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="courtreservationform",
            name="guest4FName",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="courtreservationform",
            name="guest4LName",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="courtreservationform",
            name="courtNumber",
            field=models.IntegerField(
                choices=[
                    (1, "Court 1"),
                    (2, "Court 2"),
                    (3, "Court 3"),
                    (4, "Court 4"),
                    (5, "Court 5"),
                    (6, "Court 6"),
                    (7, "Court 7"),
                    (8, "Court 8"),
                    (9, "Court 9"),
                    (10, "Court 10"),
                    (11, "Court 11"),
                    (12, "Court 12"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="courtreservationform",
            name="courtTime",
            field=models.CharField(
                choices=[
                    ("8:00 - 9:30", "8:00 - 9:30"),
                    ("9:30 - 11:00", "9:30 - 11:00"),
                    ("11:00 - 12:30", "11:00 - 12:30"),
                    ("12:30 - 2:00", "12:30 - 2:00"),
                    ("2:00 - 3:30", "2:00 - 3:30"),
                    ("3:30 - 5:00", "3:30 - 5:00"),
                ],
                max_length=20,
            ),
        ),
    ]
