# Generated by Django 4.1.6 on 2023-04-06 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courts", "0004_courtreservationform_guest4email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="courtReservationFormCourt1Time1",
            fields=[
                (
                    "courtreservationform_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="courts.courtreservationform",
                    ),
                ),
            ],
            bases=("courts.courtreservationform",),
        ),
    ]
