# Generated by Django 4.1.6 on 2023-04-08 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courts", "0005_courtreservationformcourt1time1"),
    ]

    operations = [
        migrations.DeleteModel(
            name="courtReservationFormCourt1Time1",
        ),
    ]
