# Generated by Django 4.1.6 on 2023-03-21 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_news_email_alter_news_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
