# Generated by Django 4.1.6 on 2023-04-12 03:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_addnews_story"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addnews",
            name="story",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
