# Generated by Django 4.1.6 on 2023-03-22 00:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_alter_news_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="email",
        ),
        migrations.AddField(
            model_name="news",
            name="title",
            field=models.TextField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
