# Generated by Django 4.1.6 on 2023-03-22 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0005_remove_news_id_alter_news_title"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="News",
            new_name="AddNews",
        ),
    ]
