# Generated by Django 4.1.6 on 2023-04-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0006_rename_news_addnews"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addnews",
            name="date",
            field=models.DateField(auto_now_add=True, max_length=8),
        ),
    ]
