# Generated by Django 4.1.6 on 2023-03-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_createmember_delete_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="createmember",
            name="member_id",
            field=models.IntegerField(unique=True),
        ),
    ]
