# Generated by Django 4.1.6 on 2023-04-15 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0003_alter_customuser_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="total_due",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9999),
        ),
    ]
