# Generated by Django 4.1.6 on 2023-04-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0004_customuser_total_due"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="pay_online",
            field=models.BooleanField(default=True),
        ),
    ]
