# Generated by Django 4.1.6 on 2023-03-31 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0004_alter_createmember_member_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="createmember",
            name="email_address",
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
