# Generated by Django 4.1.6 on 2023-04-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0005_customuser_pay_online"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="age",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
