# Generated by Django 4.1.6 on 2023-04-08 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0006_customuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_student",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_teacher",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="mailing_address",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
