# Generated by Django 4.1.6 on 2023-04-09 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0007_customuser_is_student_customuser_is_teacher_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
