# Generated by Django 4.1.6 on 2023-04-22 20:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0008_alter_customuser_email_alter_customuser_first_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstName", models.CharField(max_length=30)),
                ("lastName", models.CharField(max_length=30)),
                (
                    "creditCardNumber",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1000000000000000),
                            django.core.validators.MaxValueValidator(9999999999999999),
                        ]
                    ),
                ),
                ("cardExpDate", models.DateField()),
                (
                    "cvv",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(100),
                            django.core.validators.MaxValueValidator(999),
                        ]
                    ),
                ),
                (
                    "zipCode",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(10000),
                            django.core.validators.MaxValueValidator(99999),
                        ]
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="customuser",
            name="renewal",
            field=models.BooleanField(default=False),
        ),
    ]
