# Generated by Django 4.1.6 on 2023-04-22 20:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0010_alter_bill_creditcardnumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="cardExpDate",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="bill",
            name="cvv",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(100),
                    django.core.validators.MaxValueValidator(999),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="bill",
            name="zipCode",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(10000),
                    django.core.validators.MaxValueValidator(99999),
                ],
            ),
        ),
    ]
