# Generated by Django 4.1.6 on 2023-04-22 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0011_alter_bill_cardexpdate_alter_bill_cvv_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bill",
            old_name="cardExpDate",
            new_name="card_exp_date",
        ),
        migrations.RenameField(
            model_name="bill",
            old_name="creditCardNumber",
            new_name="credit_card_number",
        ),
        migrations.RenameField(
            model_name="bill",
            old_name="firstName",
            new_name="first_name",
        ),
        migrations.RenameField(
            model_name="bill",
            old_name="lastName",
            new_name="last_name",
        ),
        migrations.RenameField(
            model_name="bill",
            old_name="zipCode",
            new_name="zip_code",
        ),
    ]
