# Generated by Django 4.1.6 on 2023-04-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0014_delete_bill_customuser_card_exp_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="total_due",
            field=models.DecimalField(
                decimal_places=2, default=1000.0, max_digits=9999
            ),
        ),
    ]
