# Generated by Django 4.1.6 on 2023-04-24 01:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0017_alter_customuser_zip_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="zip_code",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(10000),
                    django.core.validators.MaxValueValidator(99999),
                ],
            ),
        ),
    ]
